const { fetchDocs } = require('./fetchDocs')

module.exports = {
  title: 'Tailwind Doc Clone',
  description: 'Tailwind CSS documentation site clone with Vitepress',
  themeConfig: {
    repo: 'https://github.com/haoranpb/vitepress-tailwind-documentation',
    pages: fetchDocs(),
    collections: {
      'Getting started': [
        'installation',
        'upgrading-to-v2',
        'using-with-preprocessors',
        'optimizing-for-production',
        'browser-support',
        'intellisense',
      ],
      'Core Concepts': [
        'utility-first',
        'responsive-design',
        'hover-focus-and-other-states',
        'dark-mode',
        'adding-base-styles',
        'extracting-components',
        'adding-new-utilities',
        'functions-and-directives',
      ],
      Customization: [
        'configuration',
        'just-in-time-mode',
        'theme',
        'breakpoints',
        'customizing-colors',
        'customizing-spacing',
        'configuring-variants',
        'plugins',
        'presets',
      ],
      'Base Styles': ['preflight'],
      Layout: [
        'container',
        'box-decoration-break',
        'box-sizing',
        'display',
        'float',
        'clear',
        'isolation',
        'object-fit',
        'object-position',
        'overflow',
        'overscroll-behavior',
        'position',
        'top-right-bottom-left',
        'visibility',
        'z-index',
      ],
      'Flexbox and Grid': [
        'flex-direction',
        'flex-wrap',
        'flex',
        'flex-grow',
        'flex-shrink',
        'order',
        'grid-template-columns',
        'grid-column',
        'grid-template-rows',
        'grid-row',
        'grid-auto-flow',
        'grid-auto-columns',
        'grid-auto-rows',
        'gap',
        'justify-content',
        'justify-items',
        'justify-self',
        'align-content',
        'align-items',
        'align-self',
        'place-content',
        'place-items',
        'place-self',
      ],
      Spacing: ['padding', 'margin', 'space'],
      Sizing: [
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
      ],
      Typography: [
        'font-family',
        'font-size',
        'font-smoothing',
        'font-style',
        'font-weight',
        'font-variant-numeric',
        'letter-spacing',
        'line-height',
        'list-style-type',
        'list-style-position',
        'placeholder-color',
        'placeholder-opacity',
        'text-align',
        'text-color',
        'text-opacity',
        'text-decoration',
        'text-transform',
        'text-overflow',
        'vertical-align',
        'whitespace',
        'word-break',
      ],
      Backgrounds: [
        'background-attachment',
        'background-clip',
        'background-color',
        'background-opacity',
        'background-position',
        'background-repeat',
        'background-size',
        'background-image',
        'gradient-color-stops',
      ],
      Borders: [
        'border-radius',
        'border-width',
        'border-color',
        'border-opacity',
        'border-style',
        'divide-width',
        'divide-color',
        'divide-opacity',
        'divide-style',
        'ring-width',
        'ring-color',
        'ring-opacity',
        'ring-offset-width',
        'ring-offset-color',
      ],
      Effects: [
        'box-shadow',
        'opacity',
        'mix-blend-mode',
        'background-blend-mode',
      ],
      Filters: [
        'filter',
        'blur',
        'brightness',
        'contrast',
        'drop-shadow',
        'grayscale',
        'hue-rotate',
        'invert',
        'saturate',
        'sepia',
        'backdrop-filter',
        'backdrop-blur',
        'backdrop-brightness',
        'backdrop-contrast',
        'backdrop-grayscale',
        'backdrop-hue-rotate',
        'backdrop-invert',
        'backdrop-opacity',
        'backdrop-saturate',
        'backdrop-sepia',
      ],
      Tables: ['border-collapse', 'table-layout'],
      'Transitions and Animation': [
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'animation',
      ],
      Transforms: [
        'transform',
        'transform-origin',
        'scale',
        'rotate',
        'translate',
        'skew',
      ],
      Interactivity: [
        'appearance',
        'cursor',
        'outline',
        'pointer-events',
        'resize',
        'user-select',
      ],
      SVG: ['fill', 'stroke', 'stroke-width'],
      Accessibility: ['screen-readers'],
    },
  },
}
